sudo: required
services:
  - docker

before_install:
  - docker build -t anilkom/react-complex-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true anilkom/react-complex-test npm test

after_success:
  - docker build -t anilkom/react-complex-client ./client
  - docker build -t anilkom/react-complex-nginx ./nginx
  - docker build -t anilkom/react-complex-api ./server
  - docker build -t anilkom/react-complex-worker ./worker

